### ISSUE TITLE
Blog Post left-hand-side line doesn't continue down the page

### ISSUE THREAD

**Issue by matthewmccullough** [github/teach.github.com#11]
The line that separates the left hand side of http://teach.github.com and its blog post entries doesn't continue to the bottom of the page.

**Comment by matthewmccullough** [comment]
![TODO](http://cl.ly/image/3G3y3e293G3O/content)

**Comment by brntbeer** [comment]
Believe this was fixed in bc2271e by @nrrrdcore! :smile_cat:

**Comment by matthewmccullough** [comment]
Beautiful! Solved. Thanks @nrrrdcore
