### ISSUE TITLE
Logo Police

### ISSUE THREAD

**Issue by benbalter** [github/teach.github.com#126]
The `.brand` element uses the old logo, which lives in `/presentations/dependencies/themes/cobalt/branding`, e.g., http://teach.github.com/presentations/github-first-look.html#/2/2

If someone could attach a PNG to this issue, glad to package up a PR, just don't have the ability to generate PNGs from https://github.com/logos.

**Comment by jordanmccullough** [comment]
![GitHub_Logo-white](https://f.cloud.github.com/assets/352082/393813/8d5240aa-a7a4-11e2-830c-d1fce637471a.png)
![GitHub_Logo-black](https://f.cloud.github.com/assets/352082/393815/8f89aeda-a7a4-11e2-97df-d3173abf2b00.png)

**Comment by jordanmccullough** [comment]
Black and white variants. Thanks for the help updating the slides.

**Comment by jordanmccullough** [comment]
@benbalter I'm attacking this PR now. So I'm closing the ticket and opening an actual PR for the update.

Thanks for flagging this necessary logo update.

**Comment by jordanmccullough** [comment]
https://github.com/github/teach.github.com/pull/132
