### ISSUE TITLE
Possible ImpressJS conversion problem

### ISSUE THREAD

**Issue by tlberglund** [github/teach.github.com#129]
There's been a bunch of merging this afternoon (some of which I've done), and in testing another open PR, I noticed this on many pages:

![image](https://f.cloud.github.com/assets/63223/393896/c69b111e-a7a6-11e2-8b50-b87721ad118d.png)

The text speaks the truth. That file is now under `_includes/hydeslides/revealjs/notes`, and does not have an equivalent version under `_includes/hydeslides/impressjs/`. @jordanmccullough, are we missing an important merge?

**Comment by jordanmccullough** [comment]
Fix forthcoming in 10 minutes. I take full responsibility for the hiccup.

**Comment by jordanmccullough** [comment]
PR fixing this out and ready.
https://github.com/github/teach.github.com/pull/130

Apologies to the team for this total oversight during the merge of the HydeSlides update. The worst should now be past us for the improvements that resulted in this.

cc/ @tlberglund @brntbeer @matthewmccullough @benbalter
