### ISSUE TITLE
Blog links return 404

### ISSUE THREAD

**Issue by nschonni** [github/teach.github.com#13]
The two blog links currently on the lefthand menu both return 404s
http://teach.github.com/blog/Refactoring
http://teach.github.com/blog/Materials-Launched

**Comment by nschonni** [comment]
One more that 404s http://teach.github.com/blog/git-cheatsheets

**Comment by matthewmccullough** [comment]
Thanks! On it. Content additions underway and I made a little mistake.

**Comment by matthewmccullough** [comment]
@nschonni I reviewed the changes and once I cleared browser cache, all seemed OK.  Feel free to re-open if so.  I did change all the URLs (nearly the last time, I promise), but we're still trying to do some big swath organization here.  I promise I respect URLs as much as anybody, so as soon as we get this last pass of normalization done, the path changing will quiet down dramatically.

**Comment by nschonni** [comment]
Thanks the slides link in the main GitHub blog still 404s after the changes as well https://github.com/blog/1282-the-github-training-web-site-is-a-thing

**Comment by matthewmccullough** [comment]
Solved as well! Nice catch. I think this is the last refactoring of the folders. Oh Betas. How they are awesome and painful at the same time.
