### ISSUE TITLE
Update Branding from "Teach" to "Teaching"

### ISSUE THREAD

**Issue by matthewmccullough** [github/teach.github.com#133]
@jsncostello did a wonderful job of laterally updating GitHub:Teach to GitHub Teach with the new Apex font in https://github.com/github/teach.github.com/pull/121. As a follow on tune-up, I'd like the phrase to read "GitHub Teaching" to fix with "GitHub Learning" and "GitHub Training".

@jsncostello Would it be possible to have you help us generate and swap the logo to "GitHub Teaching"?

**Comment by jasoncostello** [comment]
@matthewmccullough PR created, sir.

**Comment by jordanmccullough** [comment]
Reviewed and approved per https://github.com/github/teach.github.com/pull/141.

**Comment by jordanmccullough** [comment]
Thanks @jsncostello. Looks great, and the consistency for Learning, Training, Teaching is a nice touch.

**Comment by jasoncostello** [comment]
Thanks @jordanmccullough
