### ISSUE TITLE
Invalid filename characters (e.g. ?) stop contribs from Windows users

### ISSUE THREAD

**Issue by randomecho** [github/teach.github.com#139]
There are some slides in the following with question marks (?) in the filename:
- presentations/_posts/api/
- presentations/_posts/foundations/why-git-vcs

They look like they're part of the slide titles, which means it's tied there.

If you're on Windows and wanted to clone or pull the repo, you're going to see Git tell you you have some files that need deleting, which you can't stash, and probably don't want to commit.

This is only really an issue if you're working from Windows as the OS farts out when it sees these special characters.

**Comment by brntbeer** [comment]
i don't see a reason why we need the questionmarks in these file names! If you have some spare time and wanted to remove them, you could. Otherwise I'm sure one of us will get to it before the days end!

**Comment by jordanmccullough** [comment]
@randomecho and @brntbeer: Thanks for bringing this up. However, the string (dash-delimited) file names actually translate directly to slide titles. From a quick assessment, slide titles (also the file names) such as "0001-01-04-What-can-it-do?.md" make sense from my survey.

Please let me know if I'm overlooking any other cases, but the ones I did see should probably stay as-is.

Thanks again for the continued help and review.

**Comment by brntbeer** [comment]
It's the question mark that breaks on windows though, correct?

**Comment by randomecho** [comment]
Would adding it to the `title` part of the YAML front matter allow for tweaked filenames?

@brntbeer The question mark is what breaks on Windows. When fetching it it automatically deletes it as an invalid file.

**Comment by jordanmccullough** [comment]
Ah, "?" aren't allowed in Windows file names. I didn't know that.

The reason we've migrated all titles into the file names is to simplify the file naming (and what the file contains) as well as minimize the fields in the YAML.

If this is a problem with the characters in the filename for Windows, let me think about potential slide title changes that might resolve the entire thing.

Thanks again for the review and comments. Most appreciative.

**Comment by matthewmccullough** [comment]
Wondering if a title-override in the front matter would be a nice improvement for ones with symbolic needs like a question mark. Could it default to the filename and then just be over-ridden in the rare cases?  Seems like a typical programming pattern and win (override sparsely as needed).

**Comment by jordanmccullough** [comment]
@matthewmccullough Excellent idea.

@randomecho I'll just tackle this today and have the question-mark characters in filenames resolved with the solution @matthewmccullough proposed.

Thanks again!

**Comment by jordanmccullough** [comment]
PR https://github.com/github/teach.github.com/pull/140 addresses all files with "?" in them with YAML `title` field for full title and characters.

**Comment by matthewmccullough** [comment]
Crisp and clear solution. :+1: @jordanmccullough

**Comment by randomecho** [comment]
Thanks for fixing this. Git now no longer complains about instantly deleted files on rebase.
