### ISSUE TITLE
Add link to visualization tool showed at GitMerge

### ISSUE THREAD

**Issue by gurugray** [github/teach.github.com#147]
In continuation of the conversation: https://twitter.com/matthewmccull/status/333515738381955072

I can't find a proper place for the link in «Teaching Materials» lists. Is there any? :)

Just in case the link itself: https://github.com/gurugray/git-trainer

**Comment by gurugray** [comment]
@matthewmccullough need some help form you :)

**Comment by brntbeer** [comment]
A good question of where something like this should live on teach.github.com.

Traditionally i'd think it should go into http://teach.github.com/resources/, but maybe the larger problem is that we need to change some of the topics so we have an  "Additional Teaching Materials" section?

Definitely open to ideas. Love git-trainer!

**Comment by jordanmccullough** [comment]
@gurugray Thank you for sharing. I'll be speaking with the GitHub Training Team as well about placement and where this fits for Teach.GitHub.com. Appreciate the resource of your Git-Trainer.

**Comment by matthewmccullough** [comment]
@brntbeer I think that the resources page is a perfect and easy place to put this for it for the moment, but perhaps long-term as we re-merge these properties, an "Additional Teaching Materials" section makes sense.  Thinking it might be a little sparse at the moment, perhaps?  Just this, try-git, Peter Cottle's Try Git Branching, and git-immersion would be the things I'd think of at the moment in this category.

**Comment by brntbeer** [comment]
Yeah i think this should just be on resources for the time being and then we'll look at rearranging things later.

**Comment by gurugray** [comment]
Thanks to your attention to this issue and tool guys.
I'll send pullrequest for this section.
