### ISSUE TITLE
windows.github.com link sends me to mac.github.com

### ISSUE THREAD

**Issue by brntbeer** [github/teach.github.com#151]
on the foundations slide deck. the link for windows.github.com actually takes me to mac.github.com:

http://teach.github.com/presentations/git-foundations.html#/3/2

**Comment by jordanmccullough** [comment]
@brntbeer Thanks for catching this! PR awaiting approval to fix this. [PR available here](https://github.com/github/teach.github.com/pull/152).

**Comment by matthewmccullough** [comment]
Looks solved!
