### ISSUE TITLE
Two To Do sections in HydeSlides README

### ISSUE THREAD

**Issue by randomecho** [github/teach.github.com#154]
At the bottom of the [README](https://github.com/github/teach.github.com/blob/gh-pages/presentations/README.md) you have the following sections:
- To Do
- Theming
- To Do

Is having two To Do sections deliberate? One is a bracket styled checkbox list, the other is a normal list.

**Comment by jordanmccullough** [comment]
Addressing in [this PR](https://github.com/github/teach.github.com/pull/155). Thanks.
