### ISSUE TITLE
zero-indexed list shows normal numbering from 1 on Overview of GitHub Pages slides

### ISSUE THREAD

**Issue by randomecho** [github/teach.github.com#177]
In the [Overview](http://teach.github.com/presentations/github-pages.html#/1) of _GitHub Pages, Jekyll, and You!_, "The Plan" slide lists this:

```
1. 0. Setup
2. 1. GitHub Pages
3. 2. Jekyll
```

[The stylesheet](http://teach.github.com/stylesheets/slide.css) has `zero-indexed` class as reset to zero, so that shouldn't be showing with the first set of list numbers, should it?

Unless there a higher level joke going on and am just missing it.

**Comment by jordanmccullough** [comment]
Not sure why the `zero-indexed` style was applied to this `ol`, but after an assessment of the content, I've gone ahead and just tidied it up. Thanks for the watchful eye on the details @randomecho!

Fixed in 8269f720d5cc357692e38e6da69d8bb75f446f02
