### ISSUE TITLE
Check content of "Git-ing away from SVN"

### ISSUE THREAD

**Issue by matthewmccullough** [github/teach.github.com#2]
@virtualandy's written an excellent starting Gist at https://gist.github.com/3725230.

It relates to Issue #1 from @devnulled.

---
## Git-ing away from SVN

If you like using [Subversion](http://subversion.apache.org), that's awesome. We won't fault you for it (a lot). If SVN isn't enough and you'd like to migrate to Git, we want to help you through it. 

Maybe this starts with a few questions at work. Change is hard, even in software, and Git usually causes enough consternation that a few typical questions arise. We'll try to answer those, too.
### Why switch

Also known as "What's the justification", the "Why" question is common in a well established team. You're already using something - maybe it works but gets corrupted every once in a while, or is hard to administer - and introducing Git is feared because the folks in charge are afraid it's only going to get worse. And someone has to appease the folks writing the checks, too.

We've seen this phrased the following ways (if you have any additional examples, [submit a pull request](http://some_link_to_the_repo_at_github.com)). 

> Please provide justifications for the [using Git] (e.g. We should use XXX because..., and XXX is better than the others because ...)

Let's ask [Git itself](http://git-scm.com/about):

> The Git feature that really makes it stand apart from nearly every other SCM out there is its branching model.
> 
> Git allows and encourages you to have multiple local branches that can be entirely independent of each other. The creation, merging, and deletion of those lines of development takes seconds.

In practical terms, branching may give your developers a stronger feeling of freedom. Create a branch, blow it away, merge it into master with the world's greatest feature, or submit a simple bug fix. It can all be done with branches and it's only a few clicks and key presses away. And you don't have to worry about being out of sync with the one golden master.

> Notably, when you push to a remote repository, you do not have to push all of your branches. You can choose to share just one of your branches, a few of them, or all of them. This tends to free people to try new ideas without worrying about having to plan how and when they are going to merge it in or share it with others.

Git can 'free people' to be more productive, to experiment, to solve more problems. We like the sound of that. 
#### MOAR Justifications
1. [Git is small and fast](http://git-scm.com/about/small-and-fast).
2. Distributed version controls gives you [lots of alternatives and workflow options](http://git-scm.com/about/small-and-fast). Not to mention multiple repositories, in case hard drives get lost or corrupted. Even though we all know [that never happens](http://www.zdnet.com/blog/storage/data-corruption-is-worse-than-you-know/191).
3. Free as in free. [Git uses a GPLv2 license], which gives you lots of options. And plenty of freedom. There are free to read books such as [Pro Git](http://git-scm.com/book), a massively popular and wonderful hosting solution in [Github](http://github.com), tons of [great resources and documentation](http://git-scm.com/documentation/external-links) and even free tools for [using](http://code.google.com/p/tortoisegit/) or [hosting Git yourself](http://gitorious.org).

> 1.       Suggested workflows for use to use in the new system. (e.g. Managing multiple projects, managing and using common and third party libraries, and test data, simultaneously managing different development environments (Eclipse, Netbeans, Ant, etc), bringing code into classified environments, etc.
> 
> Possible systems to evaluate:
> Git
> Mercurial
> Bazaar
> Monotone
> SVN (Must include how to ensure corruptions don’t happen; not just an early detection mechanism)
> CVS
> Perforce
> ClearCase
> Others….
#### Internal Hosting

We all wish we could use [Github](http://github.com). If you're behind a firewall or in a restrictive environment, though, the public Internet site may not work. 
Thankfully, [Github](http://github.com) offers an [enterprise version](https://enterprise.github.com) that gives you the best of both worlds. 

Here's a few other options:
- one
- two
- three

[Github](http://github.com) the best place to share code with friends, co-workers, classmates, and complete strangers.

**Comment by virtualandy** [comment]
Updated a few things in [that gist](https://gist.github.com/3725230/7e2eef924f17295e0975eed1103829fa86da5018). Have at least one legit question in there, too (what's the best way to 'export' a git repo for use in an offline environment where the code may be modified, but never re-merged into master).

**Comment by virtualandy** [comment]
Turned this into a pull request. May not have done that right but would be glad to fix. :)

**Comment by matthewmccullough** [comment]
@tlberglund has merged this in via #7. I'm also editing the file directly to answer the question about export.
