### ISSUE TITLE
Foundation Class slides need logo update

### ISSUE THREAD

**Issue by jglovier** [github/teach.github.com#206]
Just noticed that the Foundation Class slides have the old logo still.

![old logo](https://github-images.s3.amazonaws.com/skitch/GrabTab-20130923-134543.png)

**Comment by jordanmccullough** [comment]
Good :eyes: @jglovier. I'm on it!

**Comment by jglovier** [comment]
![carl-sagan-youre-awesome](https://f.cloud.github.com/assets/1319791/1195620/55e7d0f8-249a-11e3-80bd-648eaed37a3a.gif)

**Comment by jordanmccullough** [comment]
![screen shot 2013-10-10 at 11 29 37 am](https://f.cloud.github.com/assets/352082/1308619/92932252-31d1-11e3-94f8-6c978643dc84.png)

**Comment by matthewmccullough** [comment]
:sparkles:
