### ISSUE TITLE
Revise Presentations' Diagram Visual Style

### ISSUE THREAD

**Issue by jordanmccullough** [github/teach.github.com#207]
Per @jglovier's [suggestion](https://github.com/github/teach.github.com/pull/204#issuecomment-24939291) for a flatter and more visually distinct way of showing the active diagram component.

This may require additional real-world projector tests to ensure contrast ratios are sufficient for the gray to appear in various viewing conditions.

![screen shot 2013-09-23 at 12 55 55 pm](https://f.cloud.github.com/assets/352082/1194232/c752f696-2481-11e3-876d-b0302e24b38f.png)

**Comment by jglovier** [comment]
:clap: :star:

**Comment by jordanmccullough** [comment]
As much as I :heart: the gray background fill look, projector tests show the black-bordered design has much higher contrast (#000 on #fff) across a variety of lighting conditions. Closing this for now unless anyone has objections.

**Comment by matthewmccullough** [comment]
I've been struggling with "poor" projectors lately and so need all the contrast I can get.

**Comment by jglovier** [comment]
:thumbsup: real use case FTW.
