### ISSUE TITLE
Teaching Materials categories (Collapsing the Training sites into fewer properties)

### ISSUE THREAD

**Issue by afeld** [github/teach.github.com#210]
When visiting the site looking for resources, I can't help feeling that the List separation isn't meaningful.  For example, the difference between "List of Presentations" and "List of Slides" isn't clear.

I wonder if a tagging/filtering system might be more useful than these distinctions?  http://teachyourselftocode.com/ is a good example of using tags to allow visitors to drill down to the type of resources they are looking for.  The things I would want to filter on are:
- Intended audience
  - Teachers vs. students
  - Experience level
- Cost
- Topic (Git, GitHub, etc.)
- Format?
  - Slides, tutorial, scheduled class, etc.

**Comment by brntbeer** [comment]
I think a restructuring of the materials would be amazeballs. Including a dedicated list view instead of a for-loop. for-loops in jekyll dont order things.

**Comment by matthewmccullough** [comment]
I think this is an excellent line of discussion, and I've been pondering and wanting to run an even more aggressive suggestion by you all.  What about dramatically pairing down what's on the site to just some top level presentations, outlines, and class notes and have some static structure that points to all three instead of the dynamic structure today?  I'm feeling ever more passionate about pruning down what's here so that the most useful things are more discoverable in line with @afeld's origin inputs, thus serving our audience better.

**Comment by tlberglund** [comment]
Completely agreed that the site is not terribly useful in its current form. The tagged idea seems like it might be doable in Jekyll.

We talk about this every so often. What the effort really needs is a motivated PRP. :)

**Comment by jordanmccullough** [comment]
I'll PRP the teach.github.com overhaul, though I must give credit to @matthewmccullough for first raising this in [the October Ship It list](https://github.com/github/outreach/discussions/11#discussion_message_15794).

**Comment by matthewmccullough** [comment]
@jordanmccullough I think the vision you and I had the other night is:
- Leave all resources "behind the scenes" so as not to break links
- Change the homepage of teach.github.com to be like our modern sites: http://gov.githubapp.com, http://edu-wip.githubapp.com
- Have three homepage (a one page site) sections that showcase symmetric resources:
  - Class outlines
  - Presentation slide decks
  - Cheat sheets

**Comment by matthewmccullough** [comment]
Cross references to this effort (some links to private repos, known) include:
- https://github.com/github/outreach/discussions/11#discussion_message_15794
- https://github.com/github/training.github.com/issues/62
- https://github.com/github/GUTS/blob/master/GUTS%202013-03-09%20Outreach%20Mini%20Summit%20Notes.md#learngithubcom-site-consolidation

**Comment by brntbeer** [comment]
:heart: for @jordanmccullough to be able to prp this

**Comment by jordanmccullough** [comment]
Moving this discussion over to the github/training.github.com [consolidated repository](https://github.com/github/training.github.com/issues/171).

https://github.com/github/training.github.com/issues/171
