### ISSUE TITLE
`?` Help on Foundations Does Not Display

### ISSUE THREAD

**Issue by jordanmccullough** [github/teach.github.com#211]
Pressing `?` or `/` on `/presentations` slide decks dims screen but help dialog fails to appear.

**Comment by tlberglund** [comment]
I observed this working as of merging #214. I think you are clear to close.

**Comment by tlberglund** [comment]
Specifically, it works on 3f8afd95bccbcdc3b6b078f76bfb2a7ca4a0de0c, which is the tip of `gh-pages` as I write this.

**Comment by jordanmccullough** [comment]
Indeed so.
