### ISSUE TITLE
Add slides for slimmed-down Foundations talk

### ISSUE THREAD

**Issue by afeld** [github/teach.github.com#223]
The Foundations deck is well-suited for a half-day class on Git/GitHub, but I (and others) have been doing 40-ish minute versions of the same thing, where the full deck becomes a burden.  Basically, a walk-though, without expecting that the attendees will be following along on their own machines.

I've created a branch that [removes many of the configuration-related steps](https://github.com/afeld/teach.github.com/compare/github:gh-pages...gh-pages#diff-9), but it could use some trimming within each chapter.  [The diagram-only deck](http://teach.github.com/presentations/git-foundations-diagrams.html) (#220) serves this purpose somewhat, but I still like having the headings for each section ("Commits", "Branches", etc.)

The main technical issue is that I don't know how to make a new HydeSlide deck that only removes _some_ of the content from each "chapter".  If it makes sense for me to simply maintain a fork, that's fine too.

Also, it could probably use a different name... "Git and GitHub: The Whirlwind Tour"?  "Up and Running"?  "GitHub Init"?

/cc @chrislundquist @jordanmccullough

**Comment by matthewmccullough** [comment]
I'm not sure if there's a way to extract certain slides just yet, but I'm thinking that at least sym-links into a second set of folders would be better than a fork.  I'd love to have the value of building/organizing a micro-class set of slides where they'd benefit all teachers and trainers.

CC: @github/training-team

**Comment by afeld** [comment]
While it might be a bit verbose for the general case, what if the slides and their hierarchy were listed explicitly in the manifest, instead of just the chapters as groups? This would probably require a change of HydeSlides, of course...

**Comment by jordanmccullough** [comment]
GitHub & Git: Up and Running, :+1: 

As for breaking chapters down into smaller bits, or selectively isolated individuals slides, that support does not yet exist in HydeSlides, but is honestly something I need to make happen. Going to give this some serious thought and see what I can do to solve it.

While I dig @matthewmccullough suggestion, the result wouldn't work as the `.md` files still have YAML front matter than contain the same tag, thus clumping them. Jekyll and HydeSlides does not honor folder structure.

**Comment by jordanmccullough** [comment]
@matthewmccullough just reminded me that we could just add another tag to identify the interesting "simple" slides and still use the "chapter" designation. And this works just as HydeSlides is right now, no code tweaks necessary.

![screen shot 2013-10-21 at 5 23 24 pm](https://f.cloud.github.com/assets/352082/1377780/55c8bc82-3ab0-11e3-9e46-619414250eb4.png)

With a tag like this on the desired "branch" chapters, for instance, another slide deck .html file could simply specify the chapters by this tag. Like so...

![screen shot 2013-10-21 at 5 26 02 pm](https://f.cloud.github.com/assets/352082/1377785/8ce379f0-3ab0-11e3-9702-d67cdf3aa3e8.png)

**Comment by afeld** [comment]
Here's an abstract for this I submitted to a conference recently: https://gist.github.com/afeld/7096908

**Comment by matthewmccullough** [comment]
@afeld Looks succinct and to the point.  Want to take a stab at adding some "simple-foundations" or similar tag to some of the slides and I'll be happy to help make that a deck with @jordanmccullough's approach above?

**Comment by afeld** [comment]
On my todo list :smile: I'm rushing to get other things done before going on vacation, so if someone else wants to take a stab, go for it!

**Comment by jordanmccullough** [comment]
@matthewmccullough I might be able to make that task happen, pending some other content refinements and HydeSlide updates.
