### ISSUE TITLE
Should we use {{page.title}} in layouts instead of having title as content

### ISSUE THREAD

**Issue by brntbeer** [github/teach.github.com#23]
Currently we have `#A Title For This Slide` in a given `.md` file, but the title is also stored in the front matter as well.

If we used the variable of `{{page.title}}` instead of keeping it in the content, this would allow more flexibility of the `{{content}}` and where we place it. This is especially useful for changing content to work along side of examples.

**Comment by matthewmccullough** [comment]
Do it!  I was trying to repeat it for visual reasons, but totally forgot about being able to use {{page.title}}  

Sharp eye.  Merge it or make it happen (as convenient)

**Comment by matthewmccullough** [comment]
Started using this in the latest `classnotes` posts.

**Comment by jordanmccullough** [comment]
Per the recent updates to the HydeSlides refresh and Teach.GitHub.com integration, all _posts should now reflect and support this 100%. There should not be any `_posts` files for slides with a YAML front matter field for `title`.

Closing since this has been addressed in the production slide decks.

**Comment by brntbeer** [comment]
Thank you for cleaning up old stuff!

:hammer:
