### ISSUE TITLE
code examples run outside of box, making box unreadable

### ISSUE THREAD

**Issue by brntbeer** [github/teach.github.com#231]
Was looking in the web inspector a bit to find out what was the deal with these slides and why they were so broken.

![screen shot 2013-11-13 at 10 39 41 pm](https://f.cloud.github.com/assets/45141/1538870/d104a812-4cf7-11e3-9792-df3b5993c58a.png)

![screen shot 2013-11-13 at 10 41 02 pm](https://f.cloud.github.com/assets/45141/1538872/d618e78c-4cf7-11e3-8a07-98edaed267c3.png)

**Comment by brntbeer** [comment]
in https://github.com/hakimel/reveal.js/blob/master/css/reveal.min.css:

`reveal .slides>section,.reveal .slides>section>section{display:none;position:absolute;width:100%;` etc, the `width:100%` here is what's causing this problem. fixed locally and it works butttttttt im not sure if want to change from what we're pulling from?

**Comment by jordanmccullough** [comment]
Will take a look today. That definitely is a problem with the overflow. I might be able to use some CSS magic to force word-wrap instead of horizontal scroll.

Thanks for catching this @brntbeer!

**Comment by brntbeer** [comment]
Well i don't know if it's a problem with the overflow attribute, the `width:100%` of that style seemed to fix things though

**Comment by jordanmccullough** [comment]
See https://github.com/github/teach.github.com/pull/242 which fixes this. :boom:
