### ISSUE TITLE
Verbatim vs summarised chat transcripts in class notes

### ISSUE THREAD

**Issue by randomecho** [github/teach.github.com#232]
Of the class notes that do include a chat transcript, some are as-is dumps from the chat. Others are somewhat a collection of questions and answers, gathered like oatmeal and laid down onto the bowl in their pairings. 

Is there a preference one way or the other on the format, if a transcript is included?

Does the transcript need to be a verbatim account of what was typed, or can it be an overview of the talking points and questions raised during the session?

**Comment by tlberglund** [comment]
@randomecho We have an internal script that sucks the transcript out of Campfire, so when it's possible to use that, a transcript is preferred _IMO_. Not that I hate on oatmeal, if you're into that sort of thing.

**Comment by jordanmccullough** [comment]
I'll want to visit this idea and classnote formatting once we have the redesign of Training.GitHub.com initiated. Thanks for bringing this up @randomecho.

Feel free to remind us again via Issues on the new learning materials and web site repo https://github.com/github/training.github.com.
