### ISSUE TITLE
"Version" and Data Storage Tree Diagram

### ISSUE THREAD

**Issue by jordanmccullough** [github/teach.github.com#233]
The Foundations deck would benefit from a diagram showing a row-column structure of commit "versions" and how full copies of files are stored per commit.

![screen shot 2013-11-19 at 9 24 23 am](https://f.cloud.github.com/assets/352082/1574043/20461f5c-5138-11e3-96f4-9c828390d232.png)

**Comment by matthewmccullough** [comment]
I've been using this diagram extensively from the [Git Internals deck](https://speakerdeck.com/matthewmccullough/git-graphs-hashes-and-compression-oh-my-1) during the [Japan Tour](https://github.com/github/trainingteam/issues/285).  I'd love to have HydeSlides versions of almost all these old decks and deprecate the Keynote ones.

**Comment by jordanmccullough** [comment]
I'm with you on that! Thanks for the reference on the Git Internals deck. I need to examine those additional resources and port ASAP.

**Comment by matthewmccullough** [comment]
No rush.  ASAP not needed.  But it would be nice as time makes this possible.

**Comment by jordanmccullough** [comment]
![git-versions](https://f.cloud.github.com/assets/352082/1602556/ccdc1c0e-5399-11e3-867e-6bea309b21f8.gif)

**Comment by matthewmccullough** [comment]
Love this. Nice to see them all in your GitHub-flavored styling.

Related thought (diagrams), but not to in any way hold this one up: a SVG design tool that could perhaps even free us from these being graphics.
- http://editor.method.ac

**Comment by jordanmccullough** [comment]
I could easily export any of the diagrams from the `presentations/src/` Illustrator files to SVG. I will investigate this for the next iteration.

For the time being, if I can get a :shipit: approval on #235 to get this important diagram it, that would be great.

Thanks for the suggestion on the SVN "path".

**Comment by matthewmccullough** [comment]
:shipit:
