### ISSUE TITLE
Port Git Internals deck to HydeSlides format

### ISSUE THREAD

**Issue by jordanmccullough** [github/teach.github.com#235]
As discussed in [#233](https://github.com/github/teach.github.com/issues/233#issuecomment-28858986), the Git Internals deck should be converted to HydeSlides format (i.e. Markdown).

**Comment by matthewmccullough** [comment]
No rush, but this would be great. This talk has been going over wonderfully in Training Team conversation.

**Comment by tlberglund** [comment]
I give this talk frequently, and do it all from Foundations diagrams and live-coded examples. I would definitely use moar illustrations if they existed, and being able to link students to a deck afterwards would be suhweet. Whenever you get to it, @jordanmccullough, this would be sooper. :)
