### ISSUE TITLE
Internationalization?

### ISSUE THREAD

**Issue by montogeek** [github/teach.github.com#237]
Is there any plan to internationalize all the contents? 

Will be great to make available this wonderful contents to anybody in the world.

**Comment by matthewmccullough** [comment]
@montogeek We don't have the talent with us to do it on our own, but if you have a strategy and would like to contribute, we'd be thrilled to have open source contributor help!

**Comment by jordanmccullough** [comment]
Moving following the migration effort of teach.github.com.

https://github.com/github/training.github.com/issues/173
