### ISSUE TITLE
Slightly misleading information re. git-cherry-pick in Advanced slides

### ISSUE THREAD

**Issue by atnan** [github/teach.github.com#28]
This is a bit of a nit pick, but @brntbeer said I should file it.

The [GitHub Git Training Slides - Advanced](http://githubtraining.s3.amazonaws.com/github-git-training-slides-advanced.pdf) linked to from the [GitHub Training Slides](https://github.com/github/teach.github.com/blob/gh-pages/slides/_posts/2001-01-01-course-slides.md) page includes some misleading information related to cherry picking.

There's a slide with the following text:

```
> git cherry-pick a5b2ee
> Merge in just one commit (not an entire branch)
```

Using the word "merge" is a misnomer, because it implies that the SHA will not change (it will). I've found this causes confusion later on when folks try and compare two branches to see what needs to be merged, and the cherry-picked commit shows up.

It might be worth using the term "apply" instead of "merge", and explaining that this isn't actually merging.

It may also be worth talking about using 'git-merge --ours/--theirs` to resolve cherry-picking SHA change issue.

**Comment by brntbeer** [comment]
:innocent: What I do?

@atnan I like the idea of using "apply". What about also having the disclaimer about the SHA changing and the compare reflecting it?

/cc @matthewmccullough for feedback as well!

**Comment by atnan** [comment]
Since this is the advanced talk, you could also mention that `git-cherry` can tell you which commits are yet to be merged even if you've used `git-cherry-pick`, because it compares based on patches (see `git-patch-id`) rather than SHAs.

**Comment by jordanmccullough** [comment]
The slides have evolved quite a bit since this was files (but thanks!). I've addressed the concern even for the present notes component of the deck.

PR here at https://github.com/github/teach.github.com/pull/166
