### ISSUE TITLE
Add link of browsers to pre-reqs

### ISSUE THREAD

**Issue by brntbeer** [github/teach.github.com#35]
We have a link in help for supported browsers, should add that to our pre-reqs articles

**Comment by jordanmccullough** [comment]
@brntbeer where are you suggesting [this](https://help.github.com/articles/supported-browsers) article be linked?

**Comment by matthewmccullough** [comment]
I think this is a good option: https://help.github.com/articles/supported-browsers

**Comment by brntbeer** [comment]
@jordanmccullough wherever we pull a list of our pre-reqs for classes from!

**Comment by jordanmccullough** [comment]
Perfect. Then this issue is ready to close. @jroll's email template already includes a link to prerequisites and the supported browsers article, so I think the situation is covered. :smile:

**Comment by brntbeer** [comment]
Yeah, would be nice to have a list in the material here for people who come to these materials though. Especially as they go to teach too, they can't get @jroll's list

**Comment by jordanmccullough** [comment]
:+1: Good point. 

I'll add the link to the [Resources](http://teach.github.com/resources/) page as that seems the most appropriate place for now.

**Comment by brntbeer** [comment]
Yessssssss. awesome! That was probably my original idea! :100:

**Comment by brntbeer** [comment]
Or something, I have no idea what i was thinking. drive-by issue reporting!
