### ISSUE TITLE
Flesh out content on PR and Org management

### ISSUE THREAD

**Issue by johndbritton** [github/teach.github.com#56]
We need some really great teaching materials that cover Pull Requests and Organization management that we can give to teachers.

**Comment by jordanmccullough** [comment]
I've got a new DZone RefCard in the works that touches on Pull Requests and general GitHub usage. One of these days I'll get around to writing some blog posts too.

**Comment by brntbeer** [comment]
I really hope you're not suggesting putting links to DZone on the site =). Stackoverflow maybe, but DZone? c'mon Jordan! haha

**Comment by jordanmccullough** [comment]
Just sayin'. It'll be out there, should students need it. :neutral_face:

**Comment by tlberglund** [comment]
It's a good thing for it to be linked and available. There are good
RefCards and bad RefCards, but this is a good one.

**Comment by brntbeer** [comment]
i know! i kid i kid, realizing this may be a bit misread!

More resources the better =)

**Comment by brntbeer** [comment]
ping @jordanmccullough, any thoughts on cleaning up the refcard for this usage?

**Comment by jordanmccullough** [comment]
The final edition of the RefCard didn't include "org" content per se, but does touch on GitHub repos, forking, and branching. Will let everyone know once it's out. Right now it's in the hands of the "editors."

**Comment by brntbeer** [comment]
Ah, had no idea there was some process on the card getting approved. Maybe
we could start on some things over at learn.github.com for now?

On Wed, Mar 13, 2013 at 12:41 PM, Jordan McCullough <
notifications@github.com> wrote:

> The final edition of the RefCard didn't include org content, but does
> touch on GitHub repos, forking, and branching. Will let everyone know once
> it's out. Right now it's in the hands of the "editors."
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/teach.github.com/issues/56#issuecomment-14863948
> .

## 

Brent Beer
GitHub:Training
http://training.github.com
https://github.com/brntbeer

**Comment by jordanmccullough** [comment]
Closing this issue in favor of PR #168 that bring some of these topics, and other GitHub-centric chapter slides into initial stages of drafts.
