### ISSUE TITLE
Basic screencasts targeted at a young audience

### ISSUE THREAD

**Issue by johndbritton** [github/teach.github.com#57]
There are lots of young people using GitHub, it'd be great to have some introductory screencasts for them to use in classrooms and at events.

**Comment by randomecho** [comment]
Could start with the ones listed at [GitCasts](http://gitcasts.com/), of the [YouTube channel](http://www.youtube.com/github), and go from there

**Comment by matthewmccullough** [comment]
This was further asked for by Arun Gupta:

https://twitter.com/arungupta/status/308056606237659136
