### ISSUE TITLE
Please switch away from the NC licensing

### ISSUE THREAD

**Issue by davelab6** [github/teach.github.com#58]
Please switch away from the NC licensing; it means I can't use these materials in training events, even ones where I'm not paid directly for the event but that are under my company branding. That's because CC says 

> You may not exercise any of the rights granted to You in Section 3 above in any manner that is primarily intended for or directed toward _commercial advantage_ or private monetary compensation.

Running even zero price events with a company brand is 'commercial advantage'. 

The homepage at http://teach.github.com/ says this license was chosen, 

> to aid schools, universities, user groups, hackathons, corporate lunch-and-learns and other educational outlets in teaching Git and GitHub

But many schools are for-profit businesses, many hackathons do private monetary compensation to organizers, and using these works in corporate lunch-and-learns is clearly for the 'commercial advantage' of the corporation.

**Comment by tlberglund** [comment]
Thanks for raising this question. We are going to revisit this issue internally right now. I hope to be back with you in a couple of days. We're very glad you're interested in using our materials!

**Comment by matthewmccullough** [comment]
@davelab6 and @brntbeer: I think we're all good here.  Glad we came to a straight-up CC-BY license.  Ready to close this (in a :100: kind of way)?

**Comment by davelab6** [comment]
Awesome! Super happy that a decision was made quickly on this :) I've made https://github.com/github/teach.github.com/pull/61 to reflect this on the index.md and then I think this is good to close!

**Comment by tlberglund** [comment]
github/teach.github.com#61 has been merged. Thanks!
