### ISSUE TITLE
List of topics on the homepage is too long and breaks the design.

### ISSUE THREAD

**Issue by matthewmccullough** [github/teach.github.com#6]
That would be awesome, and preserve the UI's beautifully designed structure.  A button under there that we can route to a view page that dynamically lists all topics would be super.

-Matthew

---

On Monday, September 17, 2012 at 8:43 AM, Julie@github.com wrote:

Hey guys!

So the Topics list on index.md is getting pretty heavy. Do you think we can limit that particular list to about 10 and then I can add a 'View All Topics' button beneath that can link to a page like topics.md? That'll give us a lot more room to make that list scannable without losing the blog or breaking the container.

---

cc: @ShepBook

**Comment by Kwpolska** [comment]
Also, I’d love to see the same thing on the topic pages.

**Comment by matthewmccullough** [comment]
@Kwpolska agreed.  Pondering a strategy on this.  I may take a stab at a Jekyll iterator and categories on each post.

**Comment by matthewmccullough** [comment]
https://github.com/github/teach.github.com/commit/daf386380377c0e32fbf16bb43648f7eb8586c07 pretty much did that, but I'm open to inputs, tuning, suggestions, and improvements. This is an rough first pass to get dynamic generation of topic pages.
