### ISSUE TITLE
Check out integrating with OnSlyde user polling

### ISSUE THREAD

**Issue by matthewmccullough** [github/teach.github.com#65]
- [ ] Test on: http://onslyde.com/devnexus/2013-HTML5.JS.APPS.html
- [ ] Test remote control: http://onslyde.com/devnexus/
- [ ] Talk to @wesleyhales about this for our next webinar

**Comment by matthewmccullough** [comment]
@jordanmccullough You should talk to Wesley here to see if we can integrate this into HydeSlides as an frontmatter parameter for the code paths.

**Comment by wesleyhales** [comment]
@matthewmccullough @jordanmccullough Hey guys, I finally got around to open sourcing this over the weekend. Check out this post for details http://wesleyhales.com/blog/2013/02/25/How-Collective-Wisdom-Shapes-a-Talk/

**Comment by wesleyhales** [comment]
Also, I can set up a private instance for the webinar to get you a smoother experience. We can talk more about it after you play around with the demo.

**Comment by jordanmccullough** [comment]
@wesleyhales Awesome! Checking this out today, as this should be something we should discuss in more detail, especially given your initial choice of RevealJS and my scaffold of Jekyll+RevealJS (HydeSlides). Will be in touch soon.

**Comment by matthewmccullough** [comment]
Open sourced!  Incredible.  Can you @ mention @ppatterns and I'll re-tweet the OSSing announcement?

I'm drowning for a week or so more on another epic set of journeys, but will carve some time out soon to talk about this with Jordan in some level of detail.

**Comment by wesleyhales** [comment]
@jordanmccullough totally, @matthewmccullough showed me HydeSlides, and that is an awesome concept. You guys talk and let me know if you need any help or have any questions.

**Comment by wesleyhales** [comment]
@matthewmccullough @jordanmccullough fyi - I quietly put up some rough draft analytics for sessions. There are still some bugs to work out and some prettifying with charts left to do.
http://onslyde.com/analytics.html

**Comment by matthewmccullough** [comment]
Way cool.

![onslyde-metrics](https://f.cloud.github.com/assets/24734/252383/639740d0-8b98-11e2-96a0-790c6dd17354.jpg)

**Comment by jordanmccullough** [comment]
Really looking forward to ways we can integrate this. Awesome work @wesleyhales. Thanks for keeping us updated and sharing.

**Comment by wesleyhales** [comment]
@matthewmccullough @jordanmccullough added some features, made a video http://youtu.be/SidOO_hgSfI and posted on HN https://news.ycombinator.com/item?id=5434207 Can you guys up vote? :beers: on me next time we meet

**Comment by wesleyhales** [comment]
Still trying to figure out best ways to visualize the data, but here's a first attempt from my session at OSCON. 
http://onslyde.com/analytics.html (enter "191" in input for oscon data and scroll to bottom)
![image](https://f.cloud.github.com/assets/429781/900759/29be075e-fb6e-11e2-8156-adc1070e0ad9.jpg)

**Comment by matthewmccullough** [comment]
@wesleyhales That's phenomenal to see a graph.  Excited to see if we could eventually engage this in our online GitHub classes as well.

**Comment by brntbeer** [comment]
hey @wesleyhales. Are you using Flot for your graphing? I'm not too familiar with it but being a bit of a data viz junky i was wondering what you thought of d3.js?

**Comment by wesleyhales** [comment]
Hey @brntbeer, I'm using highcharts in the screenshot above. I use flot in the slide deck for the bar graph/live polling results. 
I'm using d3 in another side project. There are many cool things you can do with it, but involves some polishing time to get past the basic look.
I also tried chart.js. It looks nice but doesn't have a lot of bells and whistles...very basic, with no tool tips or anything.

**Comment by brntbeer** [comment]
Ah cool, Good to know! I'm definitely not a master of d3.js, but i love it and noticed a lot of other people use it too!

**Comment by wesleyhales** [comment]
Used onslyde at Edge conf and updated the UI:
http://onslyde.com/analytics?sessionID=206 (click on points in the graph to see video)

**Comment by matthewmccullough** [comment]
@github/training-team These charts Wesley just put up would make an awesome visualization of our online classes, you think?

@jordanmccullough What would it take to carve our a day or two of your time to have a prototype of our http://teach.github.com/presentations/git-foundations.html that could send data to OnSlyde?

**Comment by tlberglund** [comment]
@wesleyhales Super cool stuff! Thanks for getting involved here. :grinning: 

@matthewmccullough Could you clarify what data we're wanting to visualize? I basically want it no matter what (so pretty are Wesley's charts), but I don't yet understand what we're trying to measure. Is it poll data?

**Comment by wesleyhales** [comment]
Thanks @matthewmccullough and @tlberglund.
Just to clarify the type of data that onslyde accepts:
- Audience sentiment. That is what you see in the chart link I pasted above. 
- Multiple choice. You can give the audience 2 options to choose from and the slides fork to the majority vote. This can also be used as a simple poll. 

At Edge conf, we used Google plus to oauth the participants. Next year they'll use that data for repeat business, such as discounts on tickets. I'm finding this is where (one of) the strengths lie; encourage participation and receive a kickback or promo of some kind.

Many routes we can go down. But I'm building out the product to suit real world usecases - so if you can think of a way to use it, I'll try to build it in.

@jordanmccullough sending data is quite easy. All you need is a session ID and proper markup in the dom: https://github.com/onslyde/onslyde/blob/master/README.md

**Comment by matthewmccullough** [comment]
@tlberglund Good to press me to clarify.  I'll write it in the form of goals:
- **Class type:** Free 45 minute monthly classes
- **Objective:** See if we're holding attention and showing interesting things throughout.
- **Data:** Scores on audience interest based on the segments of our pull request flow showcase, @mentions and other "mildly controversial" topics for newcomers to Git and GitHub.
- **Vehicle:** Have this available for HydeSlide decks where we want to gather some metrics of "interest and agreement" on the topics composing short-form online classes.

**Comment by matthewmccullough** [comment]
See also: http://coding.smashingmagazine.com/2013/11/20/reinventing-the-tech-conference-experience/comment-page-1/

**Comment by jordanmccullough** [comment]
Moving this conversation over to the new, consolidated Training repo here: https://github.com/github/training.github.com/issues/170
