### ISSUE TITLE
Screencast covering the usage of git rebase

### ISSUE THREAD

**Issue by johndbritton** [github/teach.github.com#67]
A request from @benbalter to cover git rebase in a screencast. Do we have something like this already?

**Comment by johndbritton** [comment]
http://www.youtube.com/watch?v=FyxiLdelSqc

**Comment by benbalter** [comment]
Awesome. Thanks!

Just trying to ensure @greggersh doesn't pull his hair our every time I push to master. :smile:

**Comment by greggersh** [comment]
Here's a feature request: make it so I can "like" @benbalter's above comment. ;)

**Comment by brntbeer** [comment]
@greggersh haha, just fill your comment with emoji's...clearly thats the best way.

:+1: :100: :dragon: :exclamation: :boom: :beer: :beers: :part_alternation_mark: :metal: :fire: :fireworks: :tada: 

Don't forget to look at more things at http://www.emoji-cheat-sheet.com/

Or drop im an image! 
![130831979143](https://f.cloud.github.com/assets/45141/178262/3bd9b06a-7bb1-11e2-94ce-143bc140dd42.jpeg)
