### ISSUE TITLE
Training Material for GitHub Pages

### ISSUE THREAD

**Issue by benbalter** [github/teach.github.com#70]
Perhaps I just missed it, but would be awesome to see tutorials on how to use GitHub pages. Nothing crazy, but basic I have a markdown file, and I'd love for it to be displayed as pretty HTML sort of use cases.

Potential topics to cover:
- How the URL structure works
- How the `gh-pages` branch works
- How to build a plain static site
- How Jekyll / YML / Liquid works
  - Anything that you put in the gh-pages branch will be available (unless the folder starts with an underscore). This includes HTML, CSS, JSON, whatever.
  - Anything with YML front matter at the top will be run through Jekyll.
  - If you put within the YML front matter `layout: default` (or whatever) it will look for `_layouts/default.html`. `_layouts/default.html` can be anything you want, but should have `{{ content }}` someplace in it, which will be replaced with the content
  - You can make partials in the `_includes` folder. Just include them via `{% include foo.html %}`
  - Anything in the YML front matter can be used in the file at `{{ page.foo }}`
  - Anything in `_config.yml` can be used as `{{ site.foo }}`
  - Everything above is optional
- How CNAMEs work

Again, perhaps it exists and I missed it, but would be awesome to have otherwise.

(cc @feomike)

**Edit:** Fleshed out Jekyll how to.

**Comment by brntbeer** [comment]
This is increasingly becoming more and more a good direction of training/teaching things. I love a short few pages tied together to show this. What are your feelings about a video? would each of these be a short video for a full lesson? (Sort of like asciicast for the videos?)

**Comment by benbalter** [comment]
Glad to take a first pass at the copy if it's helpful / flesh out topics a bit more (fleshed out Jekyll above a bit). 

There's the [Jekyll Documentation](https://github.com/mojombo/jekyll/wiki) that's mostly technical, and the [help articles for pages](https://help.github.com/categories/20/articles) which is mostly troubleshooting. Would be great to have a soup-to-nuts howto publish a markdown file or the like.

Re: Videos, your call. Thinking further, sounds like almost two somewhat distinct topics. One is GitHub pages, which would be creating the `gh-pages` branch, adding, committing, pushing, etc. Super simple. The other half is  more of an intro to Jekyll (covering e.g., basic templating).

**Comment by matthewmccullough** [comment]
I'd love for the @github/training-team to build something to support this request. I'd love to see folks easily enabled to use more of our features adeptly.

**Comment by benbalter** [comment]
Just chatted with @matthewmccullough and will take a first pass at this.

**Comment by benbalter** [comment]
Took a pass at outlining what this might look like. If the below looks good, can build out slides / screenshots. 

I think it may make sense to walk the viewer through building a very simple, [one or two page Jekyll site](https://github.com/benbalter/simple-site), throughout the video so things are a bit more concrete.

---

# GitHub Pages and You
- What is GitHub Pages?
  - Free static site hosting
  - Fully contained within git repository and integrated with GitHub
  - Perfect for documentation and microsites
- How does it work?
  - Special Branches
    - `gh-pages` for most pages
    - `master` for `[username].github.com` repos
  - All files transparently published by default
  - Certain files treated differently (more to come)
- Getting Started
  1. Create a new repository in your account, for now, let's call it `simple-site`
  2. Follow the instructions to clone that repository to your computer
  3. `cd` to the directory containing the repository
- Creating your first page
  1. Create an index file (e.g., `touch index.html`) and add a few words (perhaps "Hello world"?)
  2. Add the file to git (`git add index.html`)
  3. Commit the staged changes (`git commit -m 'initial commit'`)
  4. Push the changes back up to GitHub (`git push -u origin gh-pages`)
- Take a look
  1. Navigate to `http://[you-user-name].github.com/simple-site`
  2. You should now see the contents of your `index.html` file
  3. _Note: Even for private repos, pages sites are public_
- Adding some formatting
  - The index file is just an HTML file, so there's no reason we can't add some HTML and formatting
  - Take a moment to add `<html>`, `<head>`, and `<body>`, tags to the index file, and any formatting you want, such as `strong`, or `em` tags around what you originally wrote.
  - Add, commit and push, just like last time (`git add index.html`, `git commit`, `git push`)
  - The changes should now be visible in your browser if you refresh the page
- Introducing Jekyll
  - In addition to static file hosting, every push to the `gh-pages` branch is transparently run through the [Jekyll](#) templating engine
  - Since Jekyll sites are stored as static files, they are the fastest sites around and scale beautifully
  - Jekyll allows you to organize pages by common, reused layouts, and helps to build larger sites in a more manageable way
  - Don't want to use Jekyll? To disable Jekyll, simply commit a file called `.nojekyll` to the repository's root
- Jekyll Basics
  - Any file in the `gh-pages` branch of your repository will be transparently served via GitHub Pages including CSS, HTML, images, javascript, etc.
  - If you don't want a file or folder to be accessible via the web, simply start the filename with an underscore (`_`)
- YAML
  - Jekyll uses a a simply format called YAML to organize file properties
  - YAML (or YML front matter as it is also called) often lives at the top of a file surrounded by three `-` characters on the live above and below
  - Any text-bassed file, regardless of the filetype can be given YML
  - Jekyll will strip the YML front matter before serving the file via GitHub pages
  - YML front matter can control the file's presentation and is available within the template (more to come)
- Layouts
  - Jekyll's most powerful (and simplest) feature is called "layouts"
  - A layout is simply a predefiend HTML (or anything really) template which helps Jekyll render content
  - Layouts live in the `_layouts` (you may have to create this)
  - When the layout is processed, the keyword `{{ content }}` is replaced with the file's content
  - Example: Let's say you have a layout saved at `_layouts/page.html` that looks like this:

``` html
<html>
<body>
{{ content }}
</body>
</html>
```
- If we have a file saved at `/index.html` with the content `Hello World`, and add `layout: page` to the YML front matter like this:

``` html
---
layout: page
---
Hello World!
```
- When we push to GitHub pages, `/index.html`, Jekyll will replace `{{ content }}` with the actual content and generate a file that looks like this:

``` html
<html>
<body>
Hello World!
</body>
</html>
```
- Templating
  - In addition to layouts, Jekyll also provides some basic templating
  - Any field in the YML front matter can be displayed in the page using the format of `{{ page.key }}` where key is the value before the colon
  - For example, if I had `color: blue` in my YML front matter for `index.html`, I could output it by simply inserting ``{{ page.color }}` where I wanted the word blue to appear.
  - This helps to further separate the page's layout from information about the page
  - You can also add YAML to a file called `_config.yml`, and it will be available to all templates as `{{ site.key }}` using the same format
- Includes
  - The last big Jekyll feature of Jekyll is includes
  - Includes allow you to reuse common elements
  - Includes live in the `_includes` folder, and can be in any format
  - Includes can be dropped into a file using the format `{% include [file] %}`, where `[file]` is the file you want to include
  - To include `_includes/sidebar.html`, simply add `{% include sidebar.html %}` to the layout
  - Note includes use the `{% ... %}` format, while printing variables uses the `{{ ... }}` format
- Where to go from here
  - This is just the start.
  - Experiment with pretty [permalinks](https://github.com/mojombo/jekyll/wiki/Permalinks) (hint: `permalink` in a pages YML front matter will manually define its permalink)
  - Customize how Jekyll works [in the configurationn](https://github.com/mojombo/jekyll/wiki/Configuration)
  - See the [full list of template commands and filters](https://github.com/shopify/liquid/wiki/liquid-for-designers) available
  - See what other [template information](https://github.com/mojombo/jekyll/wiki/Template-Data) is available to you
  - Learn more about special [YML front matter](https://github.com/mojombo/jekyll/wiki/YAML-Front-Matter)
  - CNAME to [a custom domain](https://help.github.com/articles/setting-up-a-custom-domain-with-pages)

**Comment by brntbeer** [comment]
omg super rad.

**Comment by matthewmccullough** [comment]
@benbalter 
1. Amazing outline. I could literally teach from this.
2. This is nearer to a script. I could do a screencast right from this. I don't want to take anyone's thunder though. Did you want to record it? Are you in possession of or have access to some good audio equipment?
3. For slides, I'd be keen to see this fleshed out as a HydeSlides deck unless you have a vision for another format.  Can I show you how to drive that system if it is interesting to you? Example at: http://teach.github.com/presentations/git-foundations.html
4. Screenshots would be great.
5. There are about four directions for this.
   1. A free class: http://training.github.com/web/free-classes/
   2. A deck at: http://teach.github.com/presentations/ like http://teach.github.com/presentations/git-foundations.html
   3. A screencast at: http://youtube.com/github

Do you have a preference for first-attack vector from No. 5 above?  I want to be supportive of this happening very soon, but again, I don't want to take from anyone that wants to do this, nor "grab" anything that anyone is already planning to do.  I just want to facilitate this happening ASAP.  Love it!

**Comment by benbalter** [comment]
Ha. Thanks. :blush: Think it would be awesome if you could record a screencast on this (knowing the folks who've already asked / I'm hoping to send it to think it's the better medium), but trust you judgement if you think it's better suited for one of the other routes.

I should have time tomorrow to take a first pass at a deck based off the outline (i've used [Impress.js](http://bartaz.github.com/impress.js/#/bored), so HydeSlides shouldn't be too big a shift) and can send it your way for ultimate tweakage and recordification?

**Comment by jordanmccullough** [comment]
@benbalter Please send me a message if you need any help with [HydeSlides](http://github.com/jordanmccullough/hydeslides). My documentation is a little slim, but if you want to author the slides in Markdown and put them in a /presentations/GH-Pages folder, I can help with the rest.

**Comment by benbalter** [comment]
Also, cc @dhcole. Know you have a lot of experience walking non-technical folks through using/editing Jekyll / GitHub pages sites. Any feedback on the outline or deck?

**Comment by benbalter** [comment]
@parkr any red flags for stuff that we'd need to tweak for Jekyll 1.0 (and beyond)?

**Comment by dhcole** [comment]
@benbalter This looks awesome. Nice work.

**Comment by parkr** [comment]
@benbalter No red flags for Jekyll 1.0. You might find the new `jekyll new` command useful in a follow-up tutorial. It creates a bare-bones jekyll site in the directory you specify. You might mention the currently supported templating languages (markdown, textile, etc) for pages and posts, and run through the command-line usage for 1.0.

**Comment by benbalter** [comment]
Closing this issue in favor of #122 to keep things together.
