### ISSUE TITLE
How do I delete an issue?

### ISSUE THREAD

**Issue by geoffreyvanwyk** [github/teach.github.com#74]
I accidentally posted an issue twice, because when I submitted it the first time, I got a 404 page. How do I delete one of the issues?

**Comment by brntbeer** [comment]
Hi @systemovich,

You could simply close the other issue you have open! I've done the same kind of accidental move wayyy more than once myself!

**Comment by geoffreyvanwyk** [comment]
Hi @brntbeer 

I closed the duplicate, but I thought it would be tidy to delete it.

**Comment by brntbeer** [comment]
i see. sorry about that 404! Currently we just keep all issues are for the sake of conversation purposes and accidental deletions of such could be a bummer to people wanting them back.

Maybe a comment on the original issue mentioning it's a duplicate?

**Comment by geoffreyvanwyk** [comment]
Thanks, I will do that.
