### ISSUE TITLE
Synergize styling with training.github.com and learn.github.com

### ISSUE THREAD

**Issue by matthewmccullough** [github/teach.github.com#8]

**Comment by matthewmccullough** [comment]
Brainstormed on this at @matthewmccullough's haus on 2012-10-05

**Comment by matthewmccullough** [comment]
@nrrrdcore Is there any "color harvesting" that could be done from @cobyism's http://training.github.com to create a visual tie-in?  Just thinking bringing in a few of the blues that are over there since all of the training materials are slowing coming under one caretaking umbrella of the @github/training-team

**Comment by nrrrdcore** [comment]
Absolutely. I'll take a look when I'm back at work later this week.

**Comment by jordanmccullough** [comment]
Given that learn.github.com is now a redirect, and a teach.github.com overhaul is underway, time to close this issue?

**Comment by matthewmccullough** [comment]
@jordanmccullough :+1: from my perspective on that.
