### ISSUE TITLE
New link to be included in resources

### ISSUE THREAD

**Issue by aalbagarcia** [github/teach.github.com#82]
I'd like to suggest a new link to be included in the resources category. The link is http://www.aprendegit.com. It's a blog about git written in spanish. 

I just want to check that the category is OK before I send you the pull request.

Thanks,

Alfonso

**Comment by matthewmccullough** [comment]
Sounds correct indeed.  I might suggest something like "Spanish Language Git Education" as the name of the page that goes into this category.  It would provide a lot of options down the road for more resources to be added to it from yours and others' collections.

**Comment by matthewmccullough** [comment]
I think this was solved with https://github.com/github/teach.github.com/pull/88, so if so, feel free to close this @aalbagarcia
