### ISSUE TITLE
Category for link to www.cursodegit.com

### ISSUE THREAD

**Issue by aalbagarcia** [github/teach.github.com#83]
In http://www.cursodegit.com we organize Git and GitHub courses for freelance developers, companies and organizations in Spain. I would like to include a couple of sections with links and short descriptions of the courses we are organizing in the courses category, if you think they can be included there. If not, which category do you suggest?

Cheers,

Alfonso

**Comment by matthewmccullough** [comment]
I think that to make the page I just talked about in #82 less sparse, they might be nice companions in the single page under Resources, but if it Courses, it might be best to have a "more grand" page "Git in Languages Other Than English" to allow others to add their courses to the same (I have friend that teaches it in German, one in Swedish, and another in Norwegian that might want to participate on that page too).

**Comment by aalbagarcia** [comment]
If I understood correctly from both of your comments, the page tree would be something like this:

<pre>
\
 \Courses
 |  \
 |   - GitHub Git Online Training Preparation for XXDAYXX, 20XX-XX-XX
 |   - ...
 |   - Other Languages
 |
 \Resources
 |  \
 |    - Page for Spanish resources
 |    - Page for German resources
 |    - Page for French resources
</pre>

Is that right?

The limitation I see in this approach is that at the moment, I would have to "browse" all the categories to find all the different resources written in my language. I guess this is not a big issue since there are not so many categories and once translations are available, the user can browse the tree in her own language anyway. Also, some sort of "filter/search by language" would be great in case it's possible.

**Comment by matthewmccullough** [comment]
@aalbagarcia You are right in that it is currently a limitation, but publicly available is still better than not. :smile: We are actively working towards, in the next several months, a searchable and translation-friendly system to house these same articles, but it is a season or more out before being ready for shipping.

**Comment by aalbagarcia** [comment]
@matthewmccullough I can imagine that the translations will take some time, in the meantime, If the page tree depicted above is OK I'll prepare the pages and send you the pull request.

**Comment by matthewmccullough** [comment]
Looks good!  Go for it!

**Comment by matthewmccullough** [comment]
I think this was solved with https://github.com/github/teach.github.com/pull/88, so if so, feel free to close this @aalbagarcia
